<a href="https://colab.research.google.com/github/seongwoojang1123/Effusion-OSA-TMD/blob/main/1_data_preprocessing_Effusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

file_path = '/content/drive/MyDrive/Effusion OSA TMD/20250831_Effusion_TMD_Pain_Data.xlsx'

df = pd.read_excel(file_path, sheet_name='20250830_20250829_20250226_2024')

df.replace("", np.nan, inplace=True)

columns = df.columns
print(len(columns))
print(columns)
df.head()

21
Index(['No', 'Effusion', 'Effusion grade', 'Sex (Female)', 'Age', 'ADD', 'OA',
       'VAS', 'DI', 'PI', 'CMI', 'Symptom duration', 'TMJ noise', 'Locking',
       'Muscle stiffness', 'Tinnitus', 'Bruxism', 'Effusion_123',
       'Affected side_123', 'ADD_123', 'OA_123'],
      dtype='object')

,No,Effusion,Effusion grade,Sex (Female),Age,ADD,OA,VAS,DI,PI,...,Symptom duration,TMJ noise,Locking,Muscle stiffness,Tinnitus,Bruxism,Effusion_123,Affected side_123,ADD_123,OA_123
0,1,0,0,2,46,1,1,1,0.166667,0.000000,...,0.00,1,1,0,0,0,0,1,3,3
1,2,0,0,1,15,1,1,2,0.083333,0.000000,...,12.17,0,0,0,0,0,0,2,1,3
2,3,0,0,1,16,1,0,2,0.166667,0.000000,...,0.23,1,1,0,1,0,0,2,3,0
3,4,0,0,2,50,0,0,2,0.000000,0.000000,...,0.07,0,0,0,0,0,0,2,0,0
4,5,0,0,2,44,1,1,3,0.434524,0.214286,...,0.33,0,0,1,0,0,0,1,3,3

In [ ]:
df.describe()

,No,Effusion,Effusion grade,Sex (Female),Age,ADD,OA,VAS,DI,PI,...,Symptom duration,TMJ noise,Locking,Muscle stiffness,Tinnitus,Bruxism,Effusion_123,Affected side_123,ADD_123,OA_123
count,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,...,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000,221.000000
mean,111.000000,0.696833,0.986425,1.669683,36.027149,0.733032,0.710407,4.588235,0.266699,0.213963,...,13.940860,0.624434,0.438914,0.475113,0.321267,0.235294,1.719457,1.972851,1.968326,1.769231
std,63.941379,0.460670,0.771537,0.471395,17.962314,0.443380,0.454603,2.265883,0.238480,0.296509,...,28.193087,0.485368,0.497381,0.500514,0.468023,0.425145,1.290888,0.841636,1.305196,1.288464
min,1.000000,0.000000,0.000000,1.000000,11.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,56.000000,0.000000,0.000000,1.000000,20.000000,0.000000,0.000000,3.000000,0.083333,0.000000,...,0.670000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,111.000000,1.000000,1.000000,2.000000,35.000000,1.000000,1.000000,4.000000,0.172619,0.071429,...,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,166.000000,1.000000,2.000000,2.000000,49.000000,1.000000,1.000000,6.000000,0.369048,0.357143,...,12.170000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,3.000000,3.000000,3.000000
max,221.000000,1.000000,2.000000,2.000000,83.000000,1.000000,1.000000,10.000000,1.142857,1.714286,...,243.330000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,3.000000,3.000000,3.000000